server:
  port: 8001
spring:
  application:
    name: helloserver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
name: "黄剑"
age: "25"
address: "北京市朝阳区雅宝城"