server:
  port: 8001
spring:
  application:
    name: helloserver
  security:
    user:
      name: huangjian008
      password: 1qaZ2Wsx
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
name: "黄剑"
age: "32"
address: "贵阳市"